---
# tasks file for docker_setup

- name: Uninstall old versions
  ansible.builtin.yum:
    name: 
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent
  become: yes

- name: Install yum-utils
  ansible.builtin.yum:
    name: 
      - yum-utils
    state: present
  become: yes

- name: Add Docker Repo
  ansible.builtin.shell: |
    yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo
  become: yes

- name: Update packages
  ansible.builtin.yum:
    name: '*'
    state: latest
  become: yes

- name: Install Docker packages
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
  become: yes
 
- name: Start docker 
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Set Selinux Context
  ansible.builtin.shell:
    cmd: "docker run hello-world"
  register: docker_run_test  
  become: yes

- debug:
    var: docker_run_test.stdout
